### ISSUE TITLE
I need to analyze the LoraWan security features through simulations.

### ISSUE THREAD

**Issue by OniremE** [IOActive/laf#7]
could you give me a suggestion for me?

**Comment by matiassequeira** [comment]
Sure, we can help you. Would you describe with more details what do you need and what do you want to do?

**Comment by OniremE** [comment]
I want to analyze the possible vulnerabilities in LoraWan through simulations, packets traffic, encryption.

**Comment by matiassequeira** [comment]
Ok. The offensive part of this framework will help you to craft and inject packets into a LoRaWAN architecture but it's not meant to simulate traffic. Personally, I don't remember any repository to simulate traffic. 
Anyway, I strongly suggest you to take a quck look at shodan and look for open MQTT brokers with LoRaWAN messages, which are generated by real devices. This could be a first step! Anything else let me know.

**Comment by hjmhardsoft** [comment]
> could you give me a suggestion for me?
Hi, take a look to
https://simplesoft.com/SimpleIoTSimulator.html

**Comment by OniremE** [comment]
Thank`s, i´ll request for a demo of that software.
